M48
; DRILL file {KiCad 9.0.1} date 2025-04-14T13:02:02+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-14T13:02:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X202.525Y-64.98
X207.375Y-64.98
T2
X202.225Y-61.95
X207.675Y-61.95
M30
